import { VoiceProfile } from '../types';

export const DEFAULT_BUILTIN_VOICES: VoiceProfile[] = [
  // 🇧🇩 IndicF5 (AI4Bharat) — Bengali / Bangla
  {
    id: 'indic-bn-tariq',
    name: 'Tariq (তারিক)',
    engine: 'indic_f5',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩)',
    gender: 'male',
    category: 'preset',
    description: 'Deep, resonant, dramatic historical & storytelling voice for documentary and YouTube.',
    avatarColor: '#06b6d4',
    tags: ['Storyteller', 'Deep', 'Documentary', 'Bangla'],
  },
  {
    id: 'indic-bn-ananya',
    name: 'Ananya (অনন্যা)',
    engine: 'indic_f5',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩)',
    gender: 'female',
    category: 'preset',
    description: 'Warm, clear, natural narrative voice for audiobooks, emotional stories & explainer videos.',
    avatarColor: '#ec4899',
    tags: ['Narrative', 'Warm', 'Melodious', 'Bangla'],
  },
  {
    id: 'indic-bn-subir',
    name: 'Subir (সুবীর)',
    engine: 'indic_f5',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Crisp, authoritative broadcaster & news presentation voice.',
    avatarColor: '#3b82f6',
    tags: ['News', 'Authoritative', 'Professional', 'Bangla'],
  },
  {
    id: 'indic-bn-moushumi',
    name: 'Moushumi (মৌসুমী)',
    engine: 'indic_f5',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩)',
    gender: 'female',
    category: 'preset',
    description: 'Engaging, cheerful modern conversational creator voice.',
    avatarColor: '#a855f7',
    tags: ['Podcast', 'Conversational', 'Modern', 'Bangla'],
  },

  // 🇮🇳 IndicF5 — Other Major Indic Languages
  {
    id: 'indic-hi-aarav',
    name: 'Aarav (आरव)',
    engine: 'indic_f5',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Clear, modern Hindi narrative speaker for storytelling & tech videos.',
    avatarColor: '#f97316',
    tags: ['Hindi', 'Cinematic', 'Clear'],
  },
  {
    id: 'indic-hi-diya',
    name: 'Diya (दिया)',
    engine: 'indic_f5',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'Expressive and soft Hindi story narrator for audiobooks.',
    avatarColor: '#f43f5e',
    tags: ['Hindi', 'Expressive', 'Story'],
  },
  {
    id: 'indic-ta-kavitha',
    name: 'Kavitha (கவிதா)',
    engine: 'indic_f5',
    language: 'ta',
    languageName: 'Tamil (தமிழ் - 🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'Fluent Tamil storytelling and educational voice.',
    avatarColor: '#10b981',
    tags: ['Tamil', 'Fluent', 'Education'],
  },
  {
    id: 'indic-te-suresh',
    name: 'Suresh (సురేష్)',
    engine: 'indic_f5',
    language: 'te',
    languageName: 'Telugu (తెలుగు - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Dynamic Telugu documentary and podcast voice.',
    avatarColor: '#8b5cf6',
    tags: ['Telugu', 'Dynamic', 'Documentary'],
  },
  {
    id: 'indic-mr-rohit',
    name: 'Rohit (रोहित)',
    engine: 'indic_f5',
    language: 'mr',
    languageName: 'Marathi (मराठी - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Warm Marathi conversational tone.',
    avatarColor: '#eab308',
    tags: ['Marathi', 'Conversational'],
  },

  // 🇺🇸 / 🇬🇧 Chatterbox Multilingual (Resemble AI) — English & Global Languages
  {
    id: 'chatter-en-alexander',
    name: 'Alexander (Movie Trailer)',
    engine: 'chatterbox',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Grit, deep baritone, cinematic trailer narration with intense presence.',
    avatarColor: '#6366f1',
    tags: ['Cinematic', 'Trailer', 'Deep Baritone', 'Expressive'],
  },
  {
    id: 'chatter-en-seraphina',
    name: 'Seraphina (Audiobook Queen)',
    engine: 'chatterbox',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Expressive, soothing, emotional narrator with full vocal range and breathing.',
    avatarColor: '#d946ef',
    tags: ['Audiobook', 'Emotional', 'Expressive', 'Paralinguistic'],
  },
  {
    id: 'chatter-en-oliver',
    name: 'Oliver (British Gentleman)',
    engine: 'chatterbox',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'Refined BBC documentary presentation, polished RP English.',
    avatarColor: '#14b8a6',
    tags: ['British', 'Documentary', 'Refined', 'BBC'],
  },
  {
    id: 'chatter-en-clara',
    name: 'Clara (Dynamic Host)',
    engine: 'chatterbox',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'High energy, youthful YouTube / TikTok / Podcast creator tone.',
    avatarColor: '#f59e0b',
    tags: ['YouTube', 'Podcast', 'Upbeat', 'Energetic'],
  },
  {
    id: 'chatter-es-mateo',
    name: 'Mateo (Español)',
    engine: 'chatterbox',
    language: 'es',
    languageName: 'Spanish (Español)',
    gender: 'male',
    category: 'preset',
    description: 'Passionate and clear Spanish narrative voice.',
    avatarColor: '#ef4444',
    tags: ['Spanish', 'Dramatic', 'Clear'],
  },
  {
    id: 'chatter-fr-celeste',
    name: 'Céleste (Français)',
    engine: 'chatterbox',
    language: 'fr',
    languageName: 'French (Français)',
    gender: 'female',
    category: 'preset',
    description: 'Elegant, melodic French documentary narrator.',
    avatarColor: '#0ea5e9',
    tags: ['French', 'Elegant', 'Melodic'],
  },
  {
    id: 'chatter-ja-kenji',
    name: 'Kenji (日本語)',
    engine: 'chatterbox',
    language: 'ja',
    languageName: 'Japanese (日本語)',
    gender: 'male',
    category: 'preset',
    description: 'Calm, anime/documentary style Japanese male voice.',
    avatarColor: '#84cc16',
    tags: ['Japanese', 'Anime', 'Documentary'],
  },
  {
    id: 'chatter-de-maximilian',
    name: 'Maximilian (Deutsch)',
    engine: 'chatterbox',
    language: 'de',
    languageName: 'German (Deutsch)',
    gender: 'male',
    category: 'preset',
    description: 'Crisp, authoritative German corporate & technical narrator.',
    avatarColor: '#64748b',
    tags: ['German', 'Authoritative'],
  },
  {
    id: 'chatter-ar-tariq',
    name: 'Zayd (العربية)',
    engine: 'chatterbox',
    language: 'ar',
    languageName: 'Arabic (العربية)',
    gender: 'male',
    category: 'preset',
    description: 'Classic Arabic (Fusha) rich narrative voice.',
    avatarColor: '#059669',
    tags: ['Arabic', 'Rich', 'Classical'],
  },

  // ⚡ Microsoft Edge Neural Engine (100% Free / Ultra-Realistic Studio Quality)
  {
    id: 'edge-bn-pradeep',
    name: 'Pradeep Neural (প্রদীপ)',
    engine: 'edge_tts',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩)',
    gender: 'male',
    category: 'preset',
    description: 'Ultra-clear, authoritative studio male narrator for documentaries & history.',
    avatarColor: '#0284c7',
    tags: ['Studio', 'Bangla', 'Documentary', 'Free Neural'],
  },
  {
    id: 'edge-bn-nabanita',
    name: 'Nabanita Neural (নবনিতা)',
    engine: 'edge_tts',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩)',
    gender: 'female',
    category: 'preset',
    description: 'Warm, melodious, expressive female narrator for stories & explainer videos.',
    avatarColor: '#db2777',
    tags: ['Warm', 'Bangla', 'Storytelling', 'Free Neural'],
  },
  {
    id: 'edge-bn-bashkar',
    name: 'Bashkar Neural (ভাস্কর)',
    engine: 'edge_tts',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Rich, natural dramatic Bengali presenter and storyteller.',
    avatarColor: '#06b6d4',
    tags: ['Dramatic', 'Bangla', 'Presenter', 'Free Neural'],
  },
  {
    id: 'edge-en-christopher',
    name: 'Christopher Neural (Documentary Master)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Deep, resonant, authoritative American narrator ideal for historical documentaries.',
    avatarColor: '#4f46e5',
    tags: ['Deep', 'Documentary', 'History', 'Free Neural'],
  },
  {
    id: 'edge-en-guy',
    name: 'Guy Neural (Conversational Creator)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Natural, engaging, modern conversational YouTube / podcast presenter.',
    avatarColor: '#f59e0b',
    tags: ['Conversational', 'YouTube', 'Podcast', 'Free Neural'],
  },
  {
    id: 'edge-en-jenny',
    name: 'Jenny Neural (Story & Explainer)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Warm, highly articulate, clear and expressive female documentary narrator.',
    avatarColor: '#ec4899',
    tags: ['Warm', 'Clear', 'Audiobook', 'Free Neural'],
  },
  {
    id: 'edge-en-aria',
    name: 'Aria Neural (Dramatic Voice Actor)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Dynamic, emotional, cinematic pacing for high-stakes dramatic storytelling.',
    avatarColor: '#a855f7',
    tags: ['Dramatic', 'Cinematic', 'Emotional', 'Free Neural'],
  },
  {
    id: 'edge-en-ryan',
    name: 'Ryan Neural (British Gentleman)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'Sophisticated, classic BBC documentary British narrator with rich baritone.',
    avatarColor: '#14b8a6',
    tags: ['British', 'BBC', 'Documentary', 'Free Neural'],
  },
  {
    id: 'edge-hi-madhur',
    name: 'Madhur Neural (मधुर)',
    engine: 'edge_tts',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Polished, clear Hindi male narrator for cinema and documentaries.',
    avatarColor: '#f97316',
    tags: ['Hindi', 'Clear', 'Documentary', 'Free Neural'],
  },

  // 🏆 ElevenLabs (Broadcast & Cinematic Storytelling / Emotional Tags)
  {
    id: 'pNInz6obpgDQGcFmaJgB',
    name: 'Adam (ElevenLabs — Deep Documentary Baritone)',
    engine: 'elevenlabs',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Industry-leading deep, grave, dramatic historical narrator. Perfect for "Before It Worked".',
    avatarColor: '#e11d48',
    tags: ['ElevenLabs', 'Cinematic', 'Documentary', 'Whispers/Tags'],
  },
  {
    id: 'JBFqnCBsd6RMkjVDRZzb',
    name: 'George (ElevenLabs — British Historian)',
    engine: 'elevenlabs',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'Authentic British documentary narrator with captivating cadence and natural breaths.',
    avatarColor: '#8b5cf6',
    tags: ['ElevenLabs', 'British', 'History', 'Documentary'],
  },
  {
    id: 'FGY2WhTYpPnrIDTdsKH5',
    name: 'Marcus (ElevenLabs — Movie Trailer / Intense)',
    engine: 'elevenlabs',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Gravelly, commanding baritone for high-intensity trailers and dramatic reveals.',
    avatarColor: '#3b82f6',
    tags: ['ElevenLabs', 'Trailer', 'Deep', 'Intense'],
  },
  {
    id: '21m00Tcm4TlvDq8ikWAM',
    name: 'Rachel (ElevenLabs — Warm Narrative Queen)',
    engine: 'elevenlabs',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Warm, intimate, emotionally nuanced voice with natural human breathing.',
    avatarColor: '#ec4899',
    tags: ['ElevenLabs', 'Warm', 'Audiobook', 'Emotional'],
  },
  {
    id: 'nPczCjzI2devNBz1zQrb',
    name: 'Brian (ElevenLabs — Thoughtful Master Narrator)',
    engine: 'elevenlabs',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Thoughtful, deep, steady narrator for science, engineering & forgotten inventions.',
    avatarColor: '#10b981',
    tags: ['ElevenLabs', 'Science', 'Thoughtful', 'Documentary'],
  },

  // 🧠 OpenAI Studio Voices (tts-1-hd)
  {
    id: 'onyx',
    name: 'Onyx (OpenAI HD — Deep Baritone)',
    engine: 'openai',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Authoritative, resonant, deep male voice with exceptional studio clarity.',
    avatarColor: '#059669',
    tags: ['OpenAI', 'HD', 'Deep Baritone', 'Studio'],
  },
  {
    id: 'echo',
    name: 'Echo (OpenAI HD — Warm Balanced)',
    engine: 'openai',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Smooth, balanced conversational narrator for video essays and documentaries.',
    avatarColor: '#6366f1',
    tags: ['OpenAI', 'HD', 'Smooth', 'Conversational'],
  },
  {
    id: 'nova',
    name: 'Nova (OpenAI HD — Dynamic & Energetic)',
    engine: 'openai',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Lively, youthful, expressive female host voice with high clarity.',
    avatarColor: '#d946ef',
    tags: ['OpenAI', 'HD', 'Dynamic', 'Storyteller'],
  },
  {
    id: 'shimmer',
    name: 'Shimmer (OpenAI HD — Clear & Articulate)',
    engine: 'openai',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Crisp, articulate, emotionally resonant presentation voice.',
    avatarColor: '#0ea5e9',
    tags: ['OpenAI', 'HD', 'Crisp', 'Narration'],
  },

  // 🌐 Google AI & Cloud Speech (Gemini 2.0 Flash Audio + Google Free Studio Models)
  {
    id: 'google-gemini-aoede',
    name: 'Aoede (Google Gemini — Warm Storyteller)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Warm, melodious, deeply emotional narrative voice for audiobooks & stories.',
    avatarColor: '#ec4899',
    tags: ['Google AI', 'Gemini Audio', 'Storyteller', 'Warm', 'Free'],
  },
  {
    id: 'google-gemini-charon',
    name: 'Charon (Google Gemini — Deep Documentary Baritone)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Authoritative, resonant, deep documentary voice with natural cadence.',
    avatarColor: '#3b82f6',
    tags: ['Google AI', 'Gemini Audio', 'Deep Baritone', 'Documentary', 'Free'],
  },
  {
    id: 'google-gemini-fenrir',
    name: 'Fenrir (Google Gemini — Cinematic Trailer)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Gravelly, intense, cinematic baritone for dramatic reveals and trailers.',
    avatarColor: '#e11d48',
    tags: ['Google AI', 'Gemini Audio', 'Cinematic', 'Trailer', 'Free'],
  },
  {
    id: 'google-gemini-kore',
    name: 'Kore (Google Gemini — Articulate Host)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Calm, articulate, highly professional host tone for explainers & tutorials.',
    avatarColor: '#a855f7',
    tags: ['Google AI', 'Gemini Audio', 'Articulate', 'Explainer', 'Free'],
  },
  {
    id: 'google-gemini-puck',
    name: 'Puck (Google Gemini — Dynamic Creator)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Lively, youthful, high-energy conversational presenter for YouTube & podcasts.',
    avatarColor: '#f59e0b',
    tags: ['Google AI', 'Gemini Audio', 'YouTube', 'Conversational', 'Free'],
  },
  {
    id: 'google-bn-bashkar',
    name: 'Bashkar (Google — Bengali Presenter)',
    engine: 'google',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩/🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Natural, articulate Bengali narrator for documentary stories and videos.',
    avatarColor: '#0284c7',
    tags: ['Google Free', 'Bangla', 'Documentary', 'Natural'],
  },
  {
    id: 'google-bn-shikha',
    name: 'Shikha (Google — Bengali Melodious)',
    engine: 'google',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩/🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'Soft, melodious Bengali narrative voice for literature and explainers.',
    avatarColor: '#db2777',
    tags: ['Google Free', 'Bangla', 'Melodious', 'Narrative'],
  },
  {
    id: 'google-hi-madhur',
    name: 'Madhur (Google — Hindi Narrator)',
    engine: 'google',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Clear, modern Hindi voice for cinema commentary and educational topics.',
    avatarColor: '#f97316',
    tags: ['Google Free', 'Hindi', 'Clear', 'Educational'],
  },
  {
    id: 'google-hi-swara',
    name: 'Swara (Google — Hindi Storyteller)',
    engine: 'google',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'Expressive Hindi narrative voice with natural cadence.',
    avatarColor: '#10b981',
    tags: ['Google Free', 'Hindi', 'Storyteller', 'Expressive'],
  },
  {
    id: 'google-es-camila',
    name: 'Camila (Google — Spanish Voice)',
    engine: 'google',
    language: 'es',
    languageName: 'Spanish (Español)',
    gender: 'female',
    category: 'preset',
    description: 'Fluent, clear Spanish narrative voice for global storytelling.',
    avatarColor: '#ef4444',
    tags: ['Google Free', 'Spanish', 'Fluent'],
  },
];

