import { VoiceProfile } from '../types';
import { VOICE_SAMPLE_PROMPTS } from './voiceSamples';

const RAW_DEFAULT_BUILTIN_VOICES: VoiceProfile[] = [
  // 💎 Master Acoustic Style Blends (Kokoro-82M Curated Style Vectors)
  {
    id: 'kokoro-blend-adam-michael',
    name: 'Adam & Michael — Cinematic Documentary Baritone',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Acoustic morph of Adam (65%) & Michael (35%). Deep chest gravitas paired with modern video essay precision.',
    avatarColor: '#3b82f6',
    tags: ['Kokoro Blend', 'Deep Baritone', 'Documentary', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 0.94,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'Historical Mysteries & Documentaries',
  },
  {
    id: 'kokoro-blend-heart-bella',
    name: 'Heart, Bella & Sarah — Warm Elegance Commercial Master',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Acoustic tri-morph of Heart (55%), Bella (30%) & Sarah (15%). Warm, silky, intimate yet crystal-clear commercial presentation.',
    avatarColor: '#f43f5e',
    tags: ['Kokoro Blend', 'Style Morph', 'Broadcast Master', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 1.10,
    prosodyPacing: 'commercial',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Commercial & Ads',
    bestFor: 'High-Converting Ads & Promos',
  },
  {
    id: 'kokoro-blend-fenrir-onyx',
    name: 'Fenrir & Onyx — Cinema Movie Trailer & Dark Thriller',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Ultra-deep 45Hz sub-bass morph of Fenrir (55%), Onyx (30%) & Adam (15%). Gravelly, commanding cinematic trailer power.',
    avatarColor: '#991b1b',
    tags: ['Kokoro Blend', 'Movie Trailer', 'Deep Bass', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 0.86,
    prosodyPacing: 'trailer',
    defaultMasteringPreset: 'cinema_trailer',
    genreTag: 'Cinema & Trailer',
    bestFor: 'Movie Trailers & Dark Thrillers',
  },
  {
    id: 'kokoro-blend-george-emma',
    name: 'George & Fable — Royal BBC Master Storyteller',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'Acoustic tri-morph of George (55%), Fable (30%) & Lewis (15%). Sophisticated British historical narrator with majestic noble presence.',
    avatarColor: '#8b5cf6',
    tags: ['Kokoro Blend', 'British BBC', 'Royal Storyteller', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 0.95,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Story & Audiobook',
    bestFor: 'BBC Nature & Historical Epics',
  },
  {
    id: 'kokoro-blend-onyx-adam',
    name: 'Onyx & Adam — True Crime & Investigative Noir',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Cold, methodical, chilling investigative tone. Blend of Onyx (55%), Adam (30%) & Fenrir (15%) for true crime & noir.',
    avatarColor: '#334155',
    tags: ['Kokoro Blend', 'True Crime', 'Investigative', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 0.92,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'True Crime',
    bestFor: 'Cold Cases & Unsolved Mysteries',
  },
  {
    id: 'kokoro-blend-michael-alloy',
    name: 'Michael & Alloy — Silicon Valley Tech Explainer & AI',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Ultra-crisp, authoritative modern tech visionary delivery. Blend of Michael (55%), Alloy (30%) & Echo (15%).',
    avatarColor: '#0284c7',
    tags: ['Kokoro Blend', 'Tech Visionary', 'AI & Startups', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 1.04,
    prosodyPacing: 'commercial',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Tech & Explainer',
    bestFor: 'AI Tools, Startups & Tech Tutorials',
  },
  {
    id: 'kokoro-blend-river-heart',
    name: 'River & Heart — Meditation, Sleep & ASMR Zen',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Ultra-soft, breathy, soothing vocal cadence. Blend of River (70%) & Heart (30%) for mindfulness and deep relaxation.',
    avatarColor: '#0d9488',
    tags: ['Kokoro Blend', 'ASMR Whisper', 'Meditation', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 0.88,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'podcast_warmth',
    genreTag: 'Meditation & ASMR',
    bestFor: 'Guided Sleep & Mindfulness ASMR',
  },
  {
    id: 'kokoro-blend-puck-eric',
    name: 'Puck & Eric — High-Energy Hype & Gaming Creator',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Fast, punchy, charismatic, electric delivery. Blend of Puck (50%), Eric (35%) & Liam (15%) for TikTok, Shorts & gaming.',
    avatarColor: '#f59e0b',
    tags: ['Kokoro Blend', 'High Energy', 'Gaming Shorts', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 1.12,
    prosodyPacing: 'shorts',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Hype & Shorts',
    bestFor: 'TikTok, Shorts, Reels & Gaming Recaps',
  },
  {
    id: 'kokoro-blend-bella-aoede',
    name: 'Bella & Aoede — Emotional Memoir & Human Drama',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Poignant, vulnerable emotional depth. Blend of Bella (50%), Aoede (35%) & Heart (15%) for relationship drama & memoirs.',
    avatarColor: '#db2777',
    tags: ['Kokoro Blend', 'Emotional', 'Human Drama', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 0.94,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'podcast_warmth',
    genreTag: 'Emotional Drama',
    bestFor: 'Heartfelt Stories & Life Memoirs',
  },
  {
    id: 'kokoro-blend-emma-isabella',
    name: 'Emma & Isabella — Royal British Literary Dame',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'female',
    category: 'preset',
    description: 'Acoustic tri-morph of Emma (55%), Isabella (30%) & Alice (15%). Poetic, elegant British narration tailored for literature.',
    avatarColor: '#ec4899',
    tags: ['Kokoro Blend', 'British BBC', 'Audiobook & Drama', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 0.96,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Story & Audiobook',
    bestFor: 'Classic Literature & High Drama',
  },
  {
    id: 'kokoro-blend-lewis-george',
    name: 'Lewis & George — Cosmos & Science Professor',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'Thoughtful, intellectual British academic gravitas. Blend of Lewis (60%), George (25%) & Echo (15%) for science & philosophy.',
    avatarColor: '#6366f1',
    tags: ['Kokoro Blend', 'Science Cosmos', 'Academic British', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 0.93,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Science & Cosmos',
    bestFor: 'Astrophysics, Science & Philosophy',
  },
  {
    id: 'kokoro-blend-sarah-kore',
    name: 'Sarah & Kore — Wall Street & Financial Wealth Anchor',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Polished, high-status executive female presenter. Blend of Sarah (55%), Kore (30%) & Nicole (15%) for market analysis.',
    avatarColor: '#10b981',
    tags: ['Kokoro Blend', 'Wall Street', 'Financial News', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 1.05,
    prosodyPacing: 'commercial',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Finance & Wealth',
    bestFor: 'Business Insider, Wealth & Markets',
  },
  {
    id: 'kokoro-blend-sky-sarah',
    name: 'Sky & Sarah — Modern Dynamic Host & Podcast',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Acoustic morph of Sky (55%) & Sarah (45%). Youthful, engaging, bright podcast and YouTube creator delivery.',
    avatarColor: '#06b6d4',
    tags: ['Kokoro Blend', 'Dynamic Host', 'Podcast', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 1.00,
    prosodyPacing: 'podcast',
    defaultMasteringPreset: 'podcast_warmth',
    genreTag: 'Podcast & Host',
    bestFor: 'YouTube Podcasts & Creator Shows',
  },
  {
    id: 'kokoro-blend-echo-liam',
    name: 'Echo & Liam — Modern Video Essayist & Storyteller',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Smooth, engaging, charismatic video essay narrator. Blend of Echo (55%), Liam (30%) & Michael (15%).',
    avatarColor: '#8b5cf6',
    tags: ['Kokoro Blend', 'Video Essay', 'Storyteller', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 0.98,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Video Essay',
    bestFor: 'Film Analysis, Video Essays & Recaps',
  },
  {
    id: 'kokoro-blend-fable-adam',
    name: 'Fable & Adam — Mythic Fantasy & Epic Lorekeeper',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'British mythic cadence with resonant baritone depth. Blend of Fable (55%), Adam (30%) & Fenrir (15%).',
    avatarColor: '#7c2d12',
    tags: ['Kokoro Blend', 'Fantasy Lore', 'Epic Mythic', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 0.90,
    prosodyPacing: 'trailer',
    defaultMasteringPreset: 'cinema_trailer',
    genreTag: 'Fantasy & Lore',
    bestFor: 'D&D Lore, Fantasy Worlds & Epics',
  },
  {
    id: 'kokoro-blend-nova-jessica',
    name: 'Nova & Jessica — Upbeat Lifestyle, Travel & Vlog',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Bubbly, optimistic, vibrant female voice. Blend of Nova (55%), Jessica (30%) & Sky (15%) for lifestyle & travel.',
    avatarColor: '#ec4899',
    tags: ['Kokoro Blend', 'Lifestyle Vlog', 'Travel', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 1.08,
    prosodyPacing: 'commercial',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Lifestyle & Vlog',
    bestFor: 'Travel Vlogs, Food & Lifestyle Content',
  },
  {
    id: 'kokoro-blend-lily-heart',
    name: 'Lily & Heart — Fairytale & Kids Storybook',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'female',
    category: 'preset',
    description: 'Gentle, magical, animated British female narrator. Blend of Lily (60%) & Heart (40%) for bedtime stories.',
    avatarColor: '#a855f7',
    tags: ['Kokoro Blend', 'Kids Storybook', 'Fairytale', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 0.92,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'podcast_warmth',
    genreTag: 'Kids & Fairytale',
    bestFor: 'Children’s Audiobooks & Bedtime Tales',
  },
  {
    id: 'kokoro-blend-adam-fenrir',
    name: 'Adam & Fenrir — Mythic Lore & Deep Presence',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Acoustic morph of Adam (60%) & Fenrir (40%). Ultra-deep resonant bass with dark cinematic mystery for epics.',
    avatarColor: '#1e293b',
    tags: ['Kokoro Blend', 'Deep Mystery', 'Cinematic Lore', 'Turnkey Ready', 'Free Local'],
    defaultSpeed: 0.88,
    prosodyPacing: 'trailer',
    defaultMasteringPreset: 'cinema_trailer',
    genreTag: 'Cinema & Trailer',
    bestFor: 'Ancient Lore, Dark Epics & Legends',
  },

  // 🌟 Kokoro-82M Core Solo Voices (Hyper-Realistic Open-Source, 100% Free Local)
  {
    id: 'kokoro-af-heart',
    name: 'Heart — Ultra-Realistic Warm Female',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Ranked #1 open-source voice. Incredibly warm, natural human breathing and cadence.',
    avatarColor: '#ec4899',
    tags: ['Kokoro 82M', 'Ultra-Realistic', 'ElevenLabs Grade', 'Free Local'],
    defaultSpeed: 0.96,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'podcast_warmth',
    genreTag: 'Story & Warmth',
    bestFor: 'Emotional Storytelling & Audiobooks',
  },
  {
    id: 'kokoro-am-adam',
    name: 'Adam — Deep Documentary Baritone',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Deep, resonant, authoritative baritone for history, true crime and documentaries.',
    avatarColor: '#3b82f6',
    tags: ['Kokoro 82M', 'Deep Baritone', 'Documentary', 'Free Local'],
    defaultSpeed: 0.94,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'Historical Documentaries & Longform',
  },
  {
    id: 'kokoro-af-bella',
    name: 'Bella — Expressive Emotional Storyteller',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Dynamic, emotional storytelling voice with natural inflection and pacing.',
    avatarColor: '#f43f5e',
    tags: ['Kokoro 82M', 'Emotional', 'Storyteller', 'Free Local'],
    defaultSpeed: 0.98,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Storyteller',
    bestFor: 'Dramatic Stories & Book Narration',
  },
  {
    id: 'kokoro-am-michael',
    name: 'Michael — Articulate Commercial & Explainer',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Polished, crisp, modern narrator for business, tech, and YouTube explainers.',
    avatarColor: '#10b981',
    tags: ['Kokoro 82M', 'Clear', 'Commercial', 'Explainer', 'Free Local'],
    defaultSpeed: 1.02,
    prosodyPacing: 'commercial',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Explainer & Tech',
    bestFor: 'Corporate Explainer & Product Videos',
  },
  {
    id: 'kokoro-am-fenrir',
    name: 'Fenrir — Movie Trailer & Sub-Bass Power',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Intense, gravelly cinematic baritone with powerful sub-bass resonance.',
    avatarColor: '#7f1d1d',
    tags: ['Kokoro 82M', 'Movie Trailer', 'Sub-Bass', 'Free Local'],
    defaultSpeed: 0.88,
    prosodyPacing: 'trailer',
    defaultMasteringPreset: 'cinema_trailer',
    genreTag: 'Cinema & Trailer',
    bestFor: 'Dark Teasers & Action Trailers',
  },
  {
    id: 'kokoro-am-onyx',
    name: 'Onyx — Deep Broadcast & Investigative Baritone',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Rich, low-frequency authority designed for television broadcasts and crime journalism.',
    avatarColor: '#1e293b',
    tags: ['Kokoro 82M', 'Broadcast', 'Investigative', 'Free Local'],
    defaultSpeed: 0.95,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'True Crime',
    bestFor: 'Investigative Journalism & Reports',
  },
  {
    id: 'kokoro-am-echo',
    name: 'Echo — Smooth Video Essayist',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Warm, balanced, intimate delivery for long-form video essays and philosophical commentary.',
    avatarColor: '#6366f1',
    tags: ['Kokoro 82M', 'Video Essay', 'Conversational', 'Free Local'],
    defaultSpeed: 0.98,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Video Essay',
    bestFor: 'YouTube Video Essays & Cultural Commentary',
  },
  {
    id: 'kokoro-am-eric',
    name: 'Eric — Youthful Commercial & Fitness Hype',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Energetic, confident, athletic voice for motivation, sports, and fast-paced promos.',
    avatarColor: '#d97706',
    tags: ['Kokoro 82M', 'Energetic', 'Commercial', 'Free Local'],
    defaultSpeed: 1.06,
    prosodyPacing: 'commercial',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Commercial & Ads',
    bestFor: 'Fitness, High-Energy Ads & Sports',
  },
  {
    id: 'kokoro-am-liam',
    name: 'Liam — Movie Recap & Storytelling Momentum',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Charismatic, narrative-driven delivery built for fast-moving film recaps and viral stories.',
    avatarColor: '#4f46e5',
    tags: ['Kokoro 82M', 'Movie Recap', 'Storytelling', 'Free Local'],
    defaultSpeed: 1.04,
    prosodyPacing: 'commercial',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Video Essay',
    bestFor: 'Movie Recaps & Fast Storytelling',
  },
  {
    id: 'kokoro-am-puck',
    name: 'Puck — Witty Animated Character & Gaming',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Quirky, energetic, fast-talking personality for game streams, humor, and animations.',
    avatarColor: '#e11d48',
    tags: ['Kokoro 82M', 'Gaming', 'Animated Character', 'Free Local'],
    defaultSpeed: 1.10,
    prosodyPacing: 'shorts',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Hype & Shorts',
    bestFor: 'Gaming Guides, Shorts & Animation',
  },
  {
    id: 'kokoro-af-river',
    name: 'River — ASMR & Meditation Whisper',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Gentle, breathy, peaceful cadence ideal for relaxation, sleep hypnosis, and ASMR.',
    avatarColor: '#14b8a6',
    tags: ['Kokoro 82M', 'ASMR', 'Meditation', 'Free Local'],
    defaultSpeed: 0.88,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'podcast_warmth',
    genreTag: 'Meditation & ASMR',
    bestFor: 'Sleep Audiobooks & Zen Meditation',
  },
  {
    id: 'kokoro-af-nova',
    name: 'Nova — Bright & Dynamic Commercial',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Upbeat, modern, engaging commercial voice with infectious enthusiasm.',
    avatarColor: '#ec4899',
    tags: ['Kokoro 82M', 'Dynamic', 'Commercial', 'Free Local'],
    defaultSpeed: 1.08,
    prosodyPacing: 'commercial',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Commercial & Ads',
    bestFor: 'Product Launches & Social Media Ads',
  },
  {
    id: 'kokoro-af-sarah',
    name: 'Sarah — Professional Corporate News',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Crisp, articulate, polished corporate broadcast delivery for finance and business news.',
    avatarColor: '#059669',
    tags: ['Kokoro 82M', 'Corporate', 'News', 'Free Local'],
    defaultSpeed: 1.02,
    prosodyPacing: 'commercial',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Finance & Wealth',
    bestFor: 'Corporate Training & Business Reports',
  },
  {
    id: 'kokoro-af-sky',
    name: 'Sky — Youthful Creator & Podcast Host',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Natural, friendly, conversational delivery tailored for Gen-Z and millennial creators.',
    avatarColor: '#0284c7',
    tags: ['Kokoro 82M', 'Podcast Host', 'Creator', 'Free Local'],
    defaultSpeed: 1.02,
    prosodyPacing: 'podcast',
    defaultMasteringPreset: 'podcast_warmth',
    genreTag: 'Podcast & Host',
    bestFor: 'Casual Podcasts & Creator Vlogs',
  },
  {
    id: 'kokoro-af-nicole',
    name: 'Nicole — Articulate Educator & Teacher',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Patient, crystal-clear articulation for educational explainers and online courses.',
    avatarColor: '#7c3aed',
    tags: ['Kokoro 82M', 'Educational', 'Clear', 'Free Local'],
    defaultSpeed: 0.98,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Tech & Explainer',
    bestFor: 'Online Courses, Tutorials & Education',
  },
  {
    id: 'kokoro-af-alloy',
    name: 'Alloy — Silicon Valley Tech Narrator',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Smart, confident, balanced vocal profile tailored for SaaS and developer tutorials.',
    avatarColor: '#2563eb',
    tags: ['Kokoro 82M', 'Tech Narrator', 'SaaS', 'Free Local'],
    defaultSpeed: 1.02,
    prosodyPacing: 'commercial',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Tech & Explainer',
    bestFor: 'SaaS Walkthroughs & Tech Demos',
  },
  {
    id: 'kokoro-af-jessica',
    name: 'Jessica — Warm Conversational Lifestyle',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Relatable, cozy, engaging delivery for food, travel, wellness, and lifestyle content.',
    avatarColor: '#f59e0b',
    tags: ['Kokoro 82M', 'Lifestyle', 'Relatable', 'Free Local'],
    defaultSpeed: 1.00,
    prosodyPacing: 'podcast',
    defaultMasteringPreset: 'podcast_warmth',
    genreTag: 'Lifestyle & Vlog',
    bestFor: 'Cooking, Wellness & Lifestyle Videos',
  },
  {
    id: 'kokoro-af-kore',
    name: 'Kore — Authoritative Executive & Boardroom',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Commanding, deep female presence for corporate leadership, investor pitches, and luxury brands.',
    avatarColor: '#4338ca',
    tags: ['Kokoro 82M', 'Executive', 'Authoritative', 'Free Local'],
    defaultSpeed: 0.98,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Finance & Wealth',
    bestFor: 'Investor Pitches & Luxury Branding',
  },
  {
    id: 'kokoro-af-aoede',
    name: 'Aoede — Melodious Audiobook Narrator',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Lyrical, poetic, warm female narrator ideal for fiction, drama, and romance novels.',
    avatarColor: '#be185d',
    tags: ['Kokoro 82M', 'Audiobook', 'Poetic', 'Free Local'],
    defaultSpeed: 0.95,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'podcast_warmth',
    genreTag: 'Story & Audiobook',
    bestFor: 'Romantic Fiction & Lyrical Poetry',
  },
  {
    id: 'kokoro-bf-emma',
    name: 'Emma — British BBC Documentary Narrator',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'female',
    category: 'preset',
    description: 'Sophisticated, articulate British female voice for BBC-style documentaries.',
    avatarColor: '#8b5cf6',
    tags: ['Kokoro 82M', 'British', 'Documentary', 'BBC Style', 'Free Local'],
    defaultSpeed: 0.95,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'BBC Nature & Science Documentaries',
  },
  {
    id: 'kokoro-bm-george',
    name: 'George — British Historical Narrator',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'Commanding, cinematic British baritone for historical epics and storytelling.',
    avatarColor: '#0284c7',
    tags: ['Kokoro 82M', 'British', 'Cinematic', 'Historical', 'Free Local'],
    defaultSpeed: 0.94,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'War History & Monarchy Documentaries',
  },
  {
    id: 'kokoro-bm-fable',
    name: 'Fable — British Mythic Fantasy Storyteller',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'Rich, atmospheric British storyteller voice for fantasy chronicles and lore.',
    avatarColor: '#b45309',
    tags: ['Kokoro 82M', 'British', 'Fantasy Lore', 'Free Local'],
    defaultSpeed: 0.92,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'cinema_trailer',
    genreTag: 'Fantasy & Lore',
    bestFor: 'Fantasy Gaming, Folklore & Legends',
  },
  {
    id: 'kokoro-bm-lewis',
    name: 'Lewis — British Academic Science Professor',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'Thoughtful Oxford professor delivery with intellectual depth and precision.',
    avatarColor: '#475569',
    tags: ['Kokoro 82M', 'British', 'Academic', 'Free Local'],
    defaultSpeed: 0.94,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Science & Cosmos',
    bestFor: 'Physics, Astronomy & Scientific Research',
  },
  {
    id: 'kokoro-bm-daniel',
    name: 'Daniel — Modern British News Presenter',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'Crisp, contemporary London media presenter for tech news, finance, and journalism.',
    avatarColor: '#0891b2',
    tags: ['Kokoro 82M', 'British', 'Modern News', 'Free Local'],
    defaultSpeed: 1.02,
    prosodyPacing: 'commercial',
    defaultMasteringPreset: 'crisp_youtube',
    genreTag: 'Commercial & Ads',
    bestFor: 'Current Affairs & London Tech News',
  },
  {
    id: 'kokoro-bf-isabella',
    name: 'Isabella — British Poetic Literary Dame',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'female',
    category: 'preset',
    description: 'Aristocratic, lyrical British female delivery for poetry, costume dramas, and history.',
    avatarColor: '#9333ea',
    tags: ['Kokoro 82M', 'British', 'Poetic', 'Free Local'],
    defaultSpeed: 0.95,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Story & Audiobook',
    bestFor: 'Period Pieces, Drama & Classic Poetry',
  },
  {
    id: 'kokoro-bf-alice',
    name: 'Alice — British Classical Storyteller',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'female',
    category: 'preset',
    description: 'Gentle, refined, timeless RP English delivery for heritage documentaries.',
    avatarColor: '#c026d3',
    tags: ['Kokoro 82M', 'British', 'Classical', 'Free Local'],
    defaultSpeed: 0.96,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'podcast_warmth',
    genreTag: 'Story & Audiobook',
    bestFor: 'Victorian History & Classical Tales',
  },
  {
    id: 'kokoro-bf-lily',
    name: 'Lily — British Warm Storybook Narrator',
    engine: 'kokoro',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'female',
    category: 'preset',
    description: 'Friendly, warm, expressive British female narrator for young adult fiction and fables.',
    avatarColor: '#ea580c',
    tags: ['Kokoro 82M', 'British', 'Storybook', 'Free Local'],
    defaultSpeed: 0.94,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'podcast_warmth',
    genreTag: 'Kids & Fairytale',
    bestFor: 'Youth Audiobooks & Animated Adventures',
  },

  // 🎙️ ChatTTS (Conversational Emotion & Human Quirks)
  {
    id: 'chattts-spark',
    name: 'Spark (ChatTTS — Conversational Emotional Dialogue)',
    engine: 'chat_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'neutral',
    category: 'preset',
    description: 'Conversational AI that executes real laughter [laugh], sighs [sigh] & pauses.',
    avatarColor: '#eab308',
    tags: ['ChatTTS', 'Laughs', 'Conversational', 'Emotional', 'Free'],
  },



  // 🇧🇩 IndicF5 (AI4Bharat) — Bengali / Bangla
  {
    id: 'indic-bn-tariq',
    name: 'Tariq (তারিক)',
    engine: 'indic_f5',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩)',
    gender: 'male',
    category: 'preset',
    description: 'Deep, resonant, dramatic historical & storytelling voice for documentary and YouTube.',
    avatarColor: '#06b6d4',
    tags: ['Storyteller', 'Deep', 'Documentary', 'Bangla'],
  },
  {
    id: 'indic-bn-ananya',
    name: 'Ananya (অনন্যা)',
    engine: 'indic_f5',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩)',
    gender: 'female',
    category: 'preset',
    description: 'Warm, clear, natural narrative voice for audiobooks, emotional stories & explainer videos.',
    avatarColor: '#ec4899',
    tags: ['Narrative', 'Warm', 'Melodious', 'Bangla'],
  },
  {
    id: 'indic-bn-subir',
    name: 'Subir (সুবীর)',
    engine: 'indic_f5',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Crisp, authoritative broadcaster & news presentation voice.',
    avatarColor: '#3b82f6',
    tags: ['News', 'Authoritative', 'Professional', 'Bangla'],
  },
  {
    id: 'indic-bn-moushumi',
    name: 'Moushumi (মৌসুমী)',
    engine: 'indic_f5',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩)',
    gender: 'female',
    category: 'preset',
    description: 'Engaging, cheerful modern conversational creator voice.',
    avatarColor: '#a855f7',
    tags: ['Podcast', 'Conversational', 'Modern', 'Bangla'],
  },

  // 🇮🇳 IndicF5 — Other Major Indic Languages
  {
    id: 'indic-hi-aarav',
    name: 'Aarav (आरव)',
    engine: 'indic_f5',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Clear, modern Hindi narrative speaker for storytelling & tech videos.',
    avatarColor: '#f97316',
    tags: ['Hindi', 'Cinematic', 'Clear'],
  },
  {
    id: 'indic-hi-diya',
    name: 'Diya (दिया)',
    engine: 'indic_f5',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'Expressive and soft Hindi story narrator for audiobooks.',
    avatarColor: '#f43f5e',
    tags: ['Hindi', 'Expressive', 'Story'],
  },
  {
    id: 'indic-ta-kavitha',
    name: 'Kavitha (கவிதா)',
    engine: 'indic_f5',
    language: 'ta',
    languageName: 'Tamil (தமிழ் - 🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'Fluent Tamil storytelling and educational voice.',
    avatarColor: '#10b981',
    tags: ['Tamil', 'Fluent', 'Education'],
  },
  {
    id: 'indic-te-suresh',
    name: 'Suresh (సురేష్)',
    engine: 'indic_f5',
    language: 'te',
    languageName: 'Telugu (తెలుగు - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Dynamic Telugu documentary and podcast voice.',
    avatarColor: '#8b5cf6',
    tags: ['Telugu', 'Dynamic', 'Documentary'],
  },
  {
    id: 'indic-mr-rohit',
    name: 'Rohit (रोहित)',
    engine: 'indic_f5',
    language: 'mr',
    languageName: 'Marathi (मराठी - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Warm Marathi conversational tone.',
    avatarColor: '#eab308',
    tags: ['Marathi', 'Conversational'],
  },

  // 🇺🇸 / 🇬🇧 Chatterbox Multilingual (Resemble AI) — English & Global Languages
  {
    id: 'chatter-en-alexander',
    name: 'Alexander (Movie Trailer)',
    engine: 'chatterbox',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Grit, deep baritone, cinematic trailer narration with intense presence.',
    avatarColor: '#6366f1',
    tags: ['Cinematic', 'Trailer', 'Deep Baritone', 'Expressive'],
  },
  {
    id: 'chatter-en-seraphina',
    name: 'Seraphina (Audiobook Queen)',
    engine: 'chatterbox',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Expressive, soothing, emotional narrator with full vocal range and breathing.',
    avatarColor: '#d946ef',
    tags: ['Audiobook', 'Emotional', 'Expressive', 'Paralinguistic'],
  },
  {
    id: 'chatter-en-oliver',
    name: 'Oliver (British Gentleman)',
    engine: 'chatterbox',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'Refined BBC documentary presentation, polished RP English.',
    avatarColor: '#14b8a6',
    tags: ['British', 'Documentary', 'Refined', 'BBC'],
  },
  {
    id: 'chatter-en-clara',
    name: 'Clara (Dynamic Host)',
    engine: 'chatterbox',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'High energy, youthful YouTube / TikTok / Podcast creator tone.',
    avatarColor: '#f59e0b',
    tags: ['YouTube', 'Podcast', 'Upbeat', 'Energetic'],
  },
  {
    id: 'chatter-es-mateo',
    name: 'Mateo (Español)',
    engine: 'chatterbox',
    language: 'es',
    languageName: 'Spanish (Español)',
    gender: 'male',
    category: 'preset',
    description: 'Passionate and clear Spanish narrative voice.',
    avatarColor: '#ef4444',
    tags: ['Spanish', 'Dramatic', 'Clear'],
  },
  {
    id: 'chatter-fr-celeste',
    name: 'Céleste (Français)',
    engine: 'chatterbox',
    language: 'fr',
    languageName: 'French (Français)',
    gender: 'female',
    category: 'preset',
    description: 'Elegant, melodic French documentary narrator.',
    avatarColor: '#0ea5e9',
    tags: ['French', 'Elegant', 'Melodic'],
  },
  {
    id: 'chatter-ja-kenji',
    name: 'Kenji (日本語)',
    engine: 'chatterbox',
    language: 'ja',
    languageName: 'Japanese (日本語)',
    gender: 'male',
    category: 'preset',
    description: 'Calm, anime/documentary style Japanese male voice.',
    avatarColor: '#84cc16',
    tags: ['Japanese', 'Anime', 'Documentary'],
  },
  {
    id: 'chatter-de-maximilian',
    name: 'Maximilian (Deutsch)',
    engine: 'chatterbox',
    language: 'de',
    languageName: 'German (Deutsch)',
    gender: 'male',
    category: 'preset',
    description: 'Crisp, authoritative German corporate & technical narrator.',
    avatarColor: '#64748b',
    tags: ['German', 'Authoritative'],
  },
  {
    id: 'chatter-ar-tariq',
    name: 'Zayd (العربية)',
    engine: 'chatterbox',
    language: 'ar',
    languageName: 'Arabic (العربية)',
    gender: 'male',
    category: 'preset',
    description: 'Classic Arabic (Fusha) rich narrative voice.',
    avatarColor: '#059669',
    tags: ['Arabic', 'Rich', 'Classical'],
  },

  // ⚡ Microsoft Edge Neural Engine (100% Free / Ultra-Realistic Studio Quality)
  {
    id: 'edge-bn-pradeep',
    name: 'Pradeep Neural (প্রদীপ)',
    engine: 'edge_tts',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩)',
    gender: 'male',
    category: 'preset',
    description: 'Ultra-clear, authoritative studio male narrator for documentaries & history.',
    avatarColor: '#0284c7',
    tags: ['Studio', 'Bangla', 'Documentary', 'Free Neural'],
  },
  {
    id: 'edge-bn-nabanita',
    name: 'Nabanita Neural (নবনিতা)',
    engine: 'edge_tts',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩)',
    gender: 'female',
    category: 'preset',
    description: 'Warm, melodious, expressive female narrator for stories & explainer videos.',
    avatarColor: '#db2777',
    tags: ['Warm', 'Bangla', 'Storytelling', 'Free Neural'],
  },
  {
    id: 'edge-bn-bashkar',
    name: 'Bashkar Neural (ভাস্কর)',
    engine: 'edge_tts',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Rich, natural dramatic Bengali presenter and storyteller.',
    avatarColor: '#06b6d4',
    tags: ['Dramatic', 'Bangla', 'Presenter', 'Free Neural'],
  },
  {
    id: 'edge-bn-tanishaa',
    name: 'Tanishaa Neural (তানিশা)',
    engine: 'edge_tts',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'Natural, melodious female narrator with sweet West Bengal / Kolkata cadence — perfect for audiobooks, emotional drama & poetry.',
    avatarColor: '#f43f5e',
    tags: ['Bangla', 'Bengali', 'Kolkata', 'Melodious', 'Free Neural', 'Storytelling', '⭐ Top Pick', 'Tanisha', 'Tanishaa'],
    defaultSpeed: 1.0,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Story & Audiobook',
    bestFor: 'Audiobooks, Poetry & Drama',
  },
  {
    id: 'google-gemini-bn-charon',
    name: 'Charon (Google Gemini — বাংলা Deep Docu)',
    engine: 'google',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩/🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Deep, cinematic, resonant male narrator powered by Gemini Flash Audio for historical mysteries and documentaries.',
    avatarColor: '#1e3a8a',
    tags: ['Google Gemini', 'Bangla', 'Documentary', 'Deep Baritone', 'Free API'],
    defaultSpeed: 0.94,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'Documentaries & Mysteries',
  },
  {
    id: 'google-gemini-bn-shikha',
    name: 'Shikha (Google Gemini — বাংলা Emotional Story)',
    engine: 'google',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩/🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'Hyper-realistic emotional Bengali female narrator with authentic human pauses, gentle warmth and melodic storytelling.',
    avatarColor: '#ec4899',
    tags: ['Google Gemini', 'Bangla', 'Melodious', 'Storytelling', 'Free API'],
    defaultSpeed: 0.98,
    prosodyPacing: 'story',
    genreTag: 'Story & Audiobook',
    bestFor: 'Emotional Stories & Literature',
  },
  {
    id: 'edge-en-christopher',
    name: 'Christopher Neural (Documentary Master)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Deep, resonant, authoritative American narrator ideal for historical documentaries.',
    avatarColor: '#4f46e5',
    tags: ['Deep', 'Documentary', 'History', 'Free Neural'],
  },
  {
    id: 'edge-en-guy',
    name: 'Guy Neural (Conversational Creator)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Natural, engaging, modern conversational YouTube / podcast presenter.',
    avatarColor: '#f59e0b',
    tags: ['Conversational', 'YouTube', 'Podcast', 'Free Neural'],
  },
  {
    id: 'edge-en-jenny',
    name: 'Jenny Neural (Story & Explainer)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Warm, highly articulate, clear and expressive female documentary narrator.',
    avatarColor: '#ec4899',
    tags: ['Warm', 'Clear', 'Audiobook', 'Free Neural'],
  },
  {
    id: 'edge-en-aria',
    name: 'Aria Neural (Dramatic Voice Actor)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Dynamic, emotional, cinematic pacing for high-stakes dramatic storytelling.',
    avatarColor: '#a855f7',
    tags: ['Dramatic', 'Cinematic', 'Emotional', 'Free Neural'],
  },
  {
    id: 'edge-en-ryan',
    name: 'Ryan Neural (British Gentleman)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'Sophisticated, classic BBC documentary British narrator with rich baritone.',
    avatarColor: '#14b8a6',
    tags: ['British', 'BBC', 'Documentary', 'Free Neural'],
  },
  // ⚡ Microsoft Edge Neural — Additional Premium English Voices
  {
    id: 'edge-en-roger',
    name: 'Roger Neural (Natural Storyteller)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Most human-like Edge voice. Natural cadence, subtle warmth — perfect for long-form YouTube essays and investigative documentaries.',
    avatarColor: '#2563eb',
    tags: ['Documentary', 'YouTube', 'Human-Like', 'Free Neural', '⭐ Top Pick'],
    defaultSpeed: 0.96,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'YouTube Essays & Investigative Docs',
  },
  {
    id: 'edge-en-andrew',
    name: 'Andrew Neural (Conversational Realism)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Microsoft\'s newest multilingual neural voice. Ultra-natural, lifelike conversational realism for modern YouTube creators.',
    avatarColor: '#1d4ed8',
    tags: ['YouTube', 'Conversational', 'Multilingual', 'Free Neural', '2024 Model'],
    defaultSpeed: 1.0,
    prosodyPacing: 'commercial',
    genreTag: 'Tech & Explainer',
    bestFor: 'Vlogs, Tutorials & Modern Podcasts',
  },
  {
    id: 'edge-en-ava',
    name: 'Ava Neural (Modern Professional)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Crisp, highly professional female host with excellent articulation — ideal for explainer videos, brand content, and tutorials.',
    avatarColor: '#7c3aed',
    tags: ['Professional', 'Explainer', 'Clear', 'Free Neural', '2024 Model'],
    defaultSpeed: 1.02,
    prosodyPacing: 'commercial',
    genreTag: 'Commercial & Ads',
    bestFor: 'Brand Videos & Tutorials',
  },
  {
    id: 'edge-en-julian-sleep',
    name: 'Julian — True Deep Sleep & Bedtime Hypnotist',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Ultra-relaxing, calm-cadence hypnotic sleep voice (100–110 WPM). Tuned with natural baritone warmth, crystal-clear 3.0kHz consonant articulation, gentle de-essing, and Calm/Headspace inter-sentence pause spacing.',
    avatarColor: '#1e1b4b',
    tags: ['Deep Sleep', 'Hypnosis', 'Bedtime Stories', 'Calm Style', 'ASMR', 'Free Neural', '⭐ Top Pick'],
    defaultSpeed: 0.88,
    defaultPitch: 0,
    defaultEmotion: 'calm',
    prosodyPacing: 'sleep',
    defaultMasteringPreset: 'deep_sleep_master',
    genreTag: 'Deep Sleep',
    bestFor: 'Bedtime Stories, Sleep Hypnosis & Mindful Relaxation',
    sampleText: '[Warm, hypnotic whisper] Take a slow, deep breath in... and as you exhale, let your shoulders drop. [pause: 2.0s] Tonight, there is nowhere you need to be, and nothing you need to do. [pause: 2.5s] Just listen to the quiet, and let yourself gently drift away.',
  },
  {
    id: 'edge-en-julian-midnight',
    name: 'Julian — Late-Night Meditative Biographer',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Warm, quiet, meditative baritone calibrated at 115–125 WPM with +1.8dB chest warmth, +2.4dB consonant clarity boost, and soft de-essing for cozy, crystal-clear late-night storytelling and biographical documentaries.',
    avatarColor: '#4338ca',
    tags: ['Documentary', 'Meditative', 'Late-Night', 'Biography', 'HitoCast Style', 'Free Neural', '⭐ Top Pick'],
    defaultSpeed: 0.92,
    defaultPitch: 0,
    defaultEmotion: 'dramatic',
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'late_night_warmth',
    genreTag: 'Documentary',
    bestFor: 'Late-Night Stories & Meditative Biography',
    sampleText: '[Warm, welcoming] Hello, my friend. It is so good to have you here tonight. [pause: 0.8s] [Reflective, gentle] There was once a little boy who played football in a hotel corridor. Outside there was a war. Inside, there was a boy and his ball.',
  },
  {
    id: 'f5-en-marcus-clone',
    name: 'Marcus (F5-TTS) — ElevenLabs Studio Clone',
    engine: 'f5_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Exact zero-shot flow-matching clone of the ElevenLabs Hidocast biographical narrator. Sub-baritone 81Hz median pitch, natural vocal fry, breath inflections, and 3.3kHz consonant air. Synthesized locally on your NVIDIA GPU.',
    avatarColor: '#ea580c',
    tags: ['Marcus', 'Marcus (F5-TTS)', 'Marcus (F5-TTS Flow Matching)', 'ElevenLabs Quality', 'F5-TTS Clone', 'Deep Baritone', 'Documentary', 'Hidocast Style', '⭐ Top Pick'],
    defaultSpeed: 0.92,
    defaultPitch: 0,
    defaultEmotion: 'dramatic',
    prosodyPacing: 'story',
    defaultMasteringPreset: 'deep_cinema_warmth',
    genreTag: 'Documentary',
    bestFor: 'Authentic ElevenLabs Biographical Documentaries & Emotional Storytelling',
    referenceAudioPath: 'projects_data/voices/samples/marcus_elevenlabs_ref.wav',
    referenceText: 'Wonderful to have you here. I want to tell you a story about a boy who could not stop crying.',
    previewAudioPath: 'projects_data/voices/samples/marcus_f5_preview.wav',
    sampleText: 'Wonderful to have you here. I want to tell you a story about a boy who could not stop crying. [pause: 1.0s] Take a deep breath. Let the noise of your day grow quiet. [pause: 1.2s] This story moves through many years, and it moves through many tears.',
  },
  {
    id: 'edge-en-marcus-deep',
    name: 'Marcus — Deep Soul & Emotional Narrator (Edge Neural)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Sub-baritone emotional storyteller with natural chest warmth and clear articulation. Tuned with clause-level emotion modulation, dynamic pause pacing, and cinema mastering.',
    avatarColor: '#7c2d12',
    tags: ['Documentary', 'Emotional', 'Deep Voice', 'Free Neural', '⭐ Top Pick'],
    defaultSpeed: 0.92,
    defaultPitch: -8,
    defaultEmotion: 'dramatic',
    prosodyPacing: 'story',
    defaultMasteringPreset: 'deep_cinema_warmth',
    genreTag: 'Documentary',
    bestFor: 'Emotional Biography, Motivational Stories & Free Cloud Narration',
    sampleText: 'I want to tell you a story about a boy who could not stop crying. [pause: 1.0s] Tears of anger. [pause: 0.7s] Tears of pain. [pause: 0.9s] But also, tears of joy. [pause: 1.4s] The story begins on a small island, floating in the Atlantic. And the boy\'s name... was Cristiano.',
  },
  {
    id: 'edge-en-brian',
    name: 'Brian Neural (Thoughtful Narrator)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Measured, thoughtful, intellectually curious male voice. Excellent for science documentaries, tech explainers and philosophy content.',
    avatarColor: '#0f766e',
    tags: ['Science', 'Thoughtful', 'Documentary', 'Free Neural'],
    defaultSpeed: 0.95,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'Science & Technology Docs',
  },
  {
    id: 'edge-en-davis',
    name: 'Davis Neural (Authoritative Anchor)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Clear, composed, broadcast-anchor quality. Excellent for true crime, history, and formal documentary narration.',
    avatarColor: '#374151',
    tags: ['True Crime', 'Authoritative', 'Broadcast', 'Free Neural'],
    defaultSpeed: 0.93,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'True Crime',
    bestFor: 'Crime & History Documentaries',
  },
  {
    id: 'edge-en-emma',
    name: 'Emma Neural (Warm Host)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Friendly, engaging, warm-toned female presenter with natural pacing — ideal for YouTube lifestyle, health, and educational content.',
    avatarColor: '#be185d',
    tags: ['YouTube', 'Lifestyle', 'Warm', 'Free Neural'],
    defaultSpeed: 1.04,
    prosodyPacing: 'commercial',
    genreTag: 'Story & Audiobook',
    bestFor: 'Lifestyle, Health & Educational',
  },
  {
    id: 'edge-en-tony',
    name: 'Tony Neural (Confident Creator)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Upbeat, confident, charismatic male creator voice — perfect for top 10 lists, motivational content and high-energy YouTube.',
    avatarColor: '#b45309',
    tags: ['YouTube', 'Motivational', 'Energetic', 'Free Neural'],
    defaultSpeed: 1.06,
    prosodyPacing: 'commercial',
    genreTag: 'Tech & Explainer',
    bestFor: 'Top 10 Lists & Motivational',
  },
  {
    id: 'edge-en-nancy',
    name: 'Nancy Neural (Clear Storyteller)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Clear, articulate, calm female narrator with measured delivery — great for audiobooks, explainers and wellness content.',
    avatarColor: '#9d174d',
    tags: ['Audiobook', 'Clear', 'Calm', 'Free Neural'],
    defaultSpeed: 0.98,
    prosodyPacing: 'story',
    genreTag: 'Story & Audiobook',
    bestFor: 'Audiobooks & Wellness Content',
  },
  {
    id: 'edge-en-sara',
    name: 'Sara Neural (Cheerful Presenter)',
    engine: 'edge_tts',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Bright, cheerful, upbeat female presenter voice — great for kids content, product reviews and social media shorts.',
    avatarColor: '#d97706',
    tags: ['Social Media', 'Cheerful', 'Bright', 'Free Neural'],
    defaultSpeed: 1.08,
    prosodyPacing: 'commercial',
    genreTag: 'Commercial & Ads',
    bestFor: 'Kids Content & Social Media',
  },

  {
    id: 'edge-hi-madhur',
    name: 'Madhur Neural (मधुर)',
    engine: 'edge_tts',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Polished, clear Hindi male narrator for cinema and documentaries.',
    avatarColor: '#f97316',
    tags: ['Hindi', 'Clear', 'Documentary', 'Free Neural'],
  },
  {
    id: 'edge-hi-swara',
    name: 'Swara Neural (स्वरा)',
    engine: 'edge_tts',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'India\'s premier female neural voice. Warm, expressive, emotionally engaging storyteller and commercial host.',
    avatarColor: '#10b981',
    tags: ['Hindi', 'Expressive', 'Storyteller', 'Free Neural', '⭐ Top Pick'],
    defaultSpeed: 1.0,
    prosodyPacing: 'story',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Story & Audiobook',
    bestFor: 'Stories, Commercials & YouTube Vlogs',
  },
  {
    id: 'edge-hi-multilingual-andrew',
    name: 'Andrew Multilingual (एंड्रू — Hindi/Hinglish)',
    engine: 'edge_tts',
    language: 'hi',
    languageName: 'Hindi / Hinglish (🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Ultra-modern conversational host speaking fluent Hindi and Hinglish with natural urban creator charisma.',
    avatarColor: '#2563eb',
    tags: ['Hindi', 'Hinglish', 'YouTube Host', 'Free Neural', '2024 Model'],
    defaultSpeed: 1.02,
    prosodyPacing: 'commercial',
    genreTag: 'Tech & Explainer',
    bestFor: 'Tech Reviews, Podcasts & YouTube',
  },
  {
    id: 'edge-hi-multilingual-ava',
    name: 'Ava Multilingual (एवा — Hindi Presenter)',
    engine: 'edge_tts',
    language: 'hi',
    languageName: 'Hindi / Hinglish (🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'Crystal-clear, vibrant female host speaking fluent modern Hindi and Hinglish — perfect for tutorials, brand ads and vlogs.',
    avatarColor: '#8b5cf6',
    tags: ['Hindi', 'Hinglish', 'Modern Host', 'Free Neural', '2024 Model'],
    defaultSpeed: 1.03,
    prosodyPacing: 'commercial',
    genreTag: 'Commercial & Ads',
    bestFor: 'Brand Ads, Tutorials & Social Shorts',
  },
  {
    id: 'edge-hi-multilingual-brian',
    name: 'Brian Multilingual (ब्रायन — Hindi Science & Docu)',
    engine: 'edge_tts',
    language: 'hi',
    languageName: 'Hindi / Hinglish (🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Deep, thoughtful, analytical male narrator speaking Hindi with captivating intellectual cadence.',
    avatarColor: '#059669',
    tags: ['Hindi', 'Science', 'Documentary', 'Free Neural'],
    defaultSpeed: 0.95,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'Science Documentaries & Explainers',
  },
  {
    id: 'google-gemini-hi-charon',
    name: 'Charon (Google Gemini — हिन्दी Epic Docu)',
    engine: 'google',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Resonant, grand Hindi male documentary narrator powered by Gemini Flash Audio for historical epics and mysteries.',
    avatarColor: '#4338ca',
    tags: ['Google Gemini', 'Hindi', 'Epic', 'Documentary', 'Free API'],
    defaultSpeed: 0.92,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'Epics & Historical Documentaries',
  },
  {
    id: 'google-gemini-hi-swara',
    name: 'Swara (Google Gemini — हिन्दी Cinematic Drama)',
    engine: 'google',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'Gemini Flash Audio powered expressive Hindi female voice with authentic emotional inflections and human breath dynamics.',
    avatarColor: '#db2777',
    tags: ['Google Gemini', 'Hindi', 'Cinematic', 'Emotional', 'Free API'],
    defaultSpeed: 0.98,
    prosodyPacing: 'story',
    genreTag: 'Story & Audiobook',
    bestFor: 'Emotional Drama & Literature',
  },

  // 🏆 ElevenLabs (Broadcast & Cinematic Storytelling / Emotional Tags)
  {
    id: 'pNInz6obpgDQGcFmaJgB',
    name: 'Adam (ElevenLabs — Deep Documentary Baritone)',
    engine: 'elevenlabs',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Industry-leading deep, grave, dramatic historical narrator. Perfect for "Before It Worked".',
    avatarColor: '#e11d48',
    tags: ['ElevenLabs', 'Cinematic', 'Documentary', 'Whispers/Tags'],
  },
  {
    id: 'JBFqnCBsd6RMkjVDRZzb',
    name: 'George (ElevenLabs — British Historian)',
    engine: 'elevenlabs',
    language: 'en',
    languageName: 'English (UK)',
    gender: 'male',
    category: 'preset',
    description: 'Authentic British documentary narrator with captivating cadence and natural breaths.',
    avatarColor: '#8b5cf6',
    tags: ['ElevenLabs', 'British', 'History', 'Documentary'],
  },
  {
    id: 'FGY2WhTYpPnrIDTdsKH5',
    name: 'Marcus (ElevenLabs — Movie Trailer / Intense)',
    engine: 'elevenlabs',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Gravelly, commanding baritone for high-intensity trailers and dramatic reveals.',
    avatarColor: '#3b82f6',
    tags: ['ElevenLabs', 'Trailer', 'Deep', 'Intense'],
  },
  {
    id: '21m00Tcm4TlvDq8ikWAM',
    name: 'Rachel (ElevenLabs — Warm Narrative Queen)',
    engine: 'elevenlabs',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Warm, intimate, emotionally nuanced voice with natural human breathing.',
    avatarColor: '#ec4899',
    tags: ['ElevenLabs', 'Warm', 'Audiobook', 'Emotional'],
  },
  {
    id: 'nPczCjzI2devNBz1zQrb',
    name: 'Brian (ElevenLabs — Thoughtful Master Narrator)',
    engine: 'elevenlabs',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Thoughtful, deep, steady narrator for science, engineering & forgotten inventions.',
    avatarColor: '#10b981',
    tags: ['ElevenLabs', 'Science', 'Thoughtful', 'Documentary'],
  },

  // 🧠 OpenAI Studio Voices (tts-1-hd)
  {
    id: 'onyx',
    name: 'Onyx (OpenAI HD — Deep Baritone)',
    engine: 'openai',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Authoritative, resonant, deep male voice with exceptional studio clarity.',
    avatarColor: '#059669',
    tags: ['OpenAI', 'HD', 'Deep Baritone', 'Studio'],
  },
  {
    id: 'echo',
    name: 'Echo (OpenAI HD — Warm Balanced)',
    engine: 'openai',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Smooth, balanced conversational narrator for video essays and documentaries.',
    avatarColor: '#6366f1',
    tags: ['OpenAI', 'HD', 'Smooth', 'Conversational'],
  },
  {
    id: 'nova',
    name: 'Nova (OpenAI HD — Dynamic & Energetic)',
    engine: 'openai',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Lively, youthful, expressive female host voice with high clarity.',
    avatarColor: '#d946ef',
    tags: ['OpenAI', 'HD', 'Dynamic', 'Storyteller'],
  },
  {
    id: 'shimmer',
    name: 'Shimmer (OpenAI HD — Clear & Articulate)',
    engine: 'openai',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Crisp, articulate, emotionally resonant presentation voice.',
    avatarColor: '#0ea5e9',
    tags: ['OpenAI', 'HD', 'Crisp', 'Narration'],
  },

  // 🌐 Google AI Studio (Gemini 2.0 Flash Audio — 100% Free with Google API Key)
  {
    id: 'google-gemini-charon',
    name: 'Charon (Google AI Studio — Deep Documentary Baritone)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Deep, resonant, authoritative documentary narrator with natural human cadence and gravitas.',
    avatarColor: '#3b82f6',
    tags: ['Google AI Studio', 'Gemini Audio', 'Deep Baritone', 'Documentary', 'Free API'],
  },
  {
    id: 'google-gemini-fenrir',
    name: 'Fenrir (Google AI Studio — Cinematic Movie Trailer)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Gravelly, commanding, intense cinematic baritone for trailers and dark historical reveals.',
    avatarColor: '#e11d48',
    tags: ['Google AI Studio', 'Gemini Audio', 'Cinematic', 'Trailer', 'Free API'],
  },
  {
    id: 'google-gemini-aoede',
    name: 'Aoede (Google AI Studio — Warm Storyteller)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Warm, melodious, deeply emotional narrative voice for audiobooks & stories.',
    avatarColor: '#ec4899',
    tags: ['Google AI Studio', 'Gemini Audio', 'Storyteller', 'Warm', 'Free API'],
  },
  {
    id: 'google-gemini-puck',
    name: 'Puck (Google AI Studio — Dynamic Creator)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Lively, youthful, high-energy conversational presenter for YouTube & podcasts.',
    avatarColor: '#f59e0b',
    tags: ['Google AI Studio', 'Gemini Audio', 'YouTube', 'Conversational', 'Free API'],
  },
  {
    id: 'google-gemini-kore',
    name: 'Kore (Google AI Studio — Articulate Host)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Calm, articulate, highly professional host tone for explainers & tutorials.',
    avatarColor: '#a855f7',
    tags: ['Google AI Studio', 'Gemini Audio', 'Articulate', 'Explainer', 'Free API'],
  },
  // 🌐 Google Gemini TTS — Additional 25 Voices (Complete 30-Voice Set)
  {
    id: 'google-gemini-zephyr',
    name: 'Zephyr (Google AI Studio — Bright & Breezy)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Light, breezy, naturally expressive voice with a youthful energy — great for lifestyle and travel YouTube.',
    avatarColor: '#06b6d4',
    tags: ['Google AI Studio', 'Gemini Audio', 'Bright', 'Lifestyle', 'Free API'],
    defaultSpeed: 1.05,
    prosodyPacing: 'commercial',
    genreTag: 'Commercial & Ads',
    bestFor: 'Lifestyle & Travel Content',
  },
  {
    id: 'google-gemini-leda',
    name: 'Leda (Google AI Studio — Youthful & Clear)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Young, crisp, clear female voice with upbeat delivery — ideal for social media, product reviews and trendy YouTube content.',
    avatarColor: '#f472b6',
    tags: ['Google AI Studio', 'Gemini Audio', 'Youthful', 'Social Media', 'Free API'],
    defaultSpeed: 1.06,
    prosodyPacing: 'commercial',
    genreTag: 'Commercial & Ads',
    bestFor: 'TikTok, Shorts & Social Media',
  },
  {
    id: 'google-gemini-orus',
    name: 'Orus (Google AI Studio — Bold & Confident)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Bold, confident, assertive baritone with strong presence — great for motivational and business content.',
    avatarColor: '#dc2626',
    tags: ['Google AI Studio', 'Gemini Audio', 'Bold', 'Motivational', 'Free API'],
    defaultSpeed: 0.97,
    prosodyPacing: 'commercial',
    genreTag: 'Tech & Explainer',
    bestFor: 'Business & Motivational Content',
  },
  {
    id: 'google-gemini-umbriel',
    name: 'Umbriel (Google AI Studio — Calm & Deep)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Calm, deep, measured delivery with natural cadence — excellent for meditation, philosophical and educational content.',
    avatarColor: '#4338ca',
    tags: ['Google AI Studio', 'Gemini Audio', 'Calm', 'Meditation', 'Free API'],
    defaultSpeed: 0.90,
    prosodyPacing: 'story',
    genreTag: 'Story & Audiobook',
    bestFor: 'Meditation & Education',
  },
  {
    id: 'google-gemini-iapetus',
    name: 'Iapetus (Google AI Studio — Epic Narrator)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Epic, resonant, grand documentary narrator — ideal for space, science and historical epic documentaries.',
    avatarColor: '#7c3aed',
    tags: ['Google AI Studio', 'Gemini Audio', 'Epic', 'Documentary', 'Free API'],
    defaultSpeed: 0.88,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'Space, Science & Historical Epics',
  },
  {
    id: 'google-gemini-schedar',
    name: 'Schedar (Google AI Studio — Steady Anchor)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Steady, trustworthy, broadcast-anchor quality with clear authoritative delivery.',
    avatarColor: '#0369a1',
    tags: ['Google AI Studio', 'Gemini Audio', 'Authoritative', 'Broadcast', 'Free API'],
    defaultSpeed: 0.94,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'True Crime',
    bestFor: 'News-Style & True Crime Content',
  },
  {
    id: 'google-gemini-vindemiatrix',
    name: 'Vindemiatrix (Google AI Studio — Wise Storyteller)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Wise, mature, deeply expressive female narrator with gravitas — ideal for historical and spiritual content.',
    avatarColor: '#92400e',
    tags: ['Google AI Studio', 'Gemini Audio', 'Wise', 'Historical', 'Free API'],
    defaultSpeed: 0.92,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'Historical & Spiritual Documentaries',
  },
  {
    id: 'google-gemini-gacrux',
    name: 'Gacrux (Google AI Studio — Mature & Rich)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Rich, mature, full-bodied baritone with warm timbre — great for audiobooks and long-form documentary.',
    avatarColor: '#854d0e',
    tags: ['Google AI Studio', 'Gemini Audio', 'Rich Baritone', 'Audiobook', 'Free API'],
    defaultSpeed: 0.93,
    prosodyPacing: 'story',
    genreTag: 'Story & Audiobook',
    bestFor: 'Audiobooks & Long-Form Narration',
  },
  {
    id: 'google-gemini-laomedeia',
    name: 'Laomedeia (Google AI Studio — Elegant & Soft)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Elegant, soft, refined female voice with luxurious tone — perfect for premium brands, wellness and ASMR.',
    avatarColor: '#9d174d',
    tags: ['Google AI Studio', 'Gemini Audio', 'Elegant', 'ASMR', 'Free API'],
    defaultSpeed: 0.88,
    prosodyPacing: 'story',
    genreTag: 'Story & Audiobook',
    bestFor: 'Wellness, ASMR & Premium Brands',
  },
  {
    id: 'google-gemini-erinome',
    name: 'Erinome (Google AI Studio — Vivid & Expressive)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Vivid, expressive, emotionally dynamic female narrator with theatrical range — excellent for fiction audiobooks.',
    avatarColor: '#a21caf',
    tags: ['Google AI Studio', 'Gemini Audio', 'Expressive', 'Fiction', 'Free API'],
    defaultSpeed: 0.96,
    prosodyPacing: 'story',
    genreTag: 'Story & Audiobook',
    bestFor: 'Fiction Audiobooks & Drama',
  },
  {
    id: 'google-gemini-despina',
    name: 'Despina (Google AI Studio — Playful & Warm)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Playful, warm, natural conversational female voice — ideal for kids education, family content and fun tutorials.',
    avatarColor: '#d97706',
    tags: ['Google AI Studio', 'Gemini Audio', 'Playful', 'Kids', 'Free API'],
    defaultSpeed: 1.05,
    prosodyPacing: 'commercial',
    genreTag: 'Commercial & Ads',
    bestFor: 'Kids Content & Family Videos',
  },
  {
    id: 'google-gemini-callirrhoe',
    name: 'Callirrhoe (Google AI Studio — Serene & Melodic)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Serene, melodic, flowing female narrator — superb for nature documentaries, meditation and ambient storytelling.',
    avatarColor: '#065f46',
    tags: ['Google AI Studio', 'Gemini Audio', 'Serene', 'Nature', 'Free API'],
    defaultSpeed: 0.87,
    prosodyPacing: 'story',
    genreTag: 'Story & Audiobook',
    bestFor: 'Nature Docs & Meditation',
  },
  {
    id: 'google-gemini-autonoe',
    name: 'Autonoe (Google AI Studio — Bright & Energetic)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Bright, energetic, fast-paced female presenter — great for news summaries, quick explainers and social shorts.',
    avatarColor: '#f59e0b',
    tags: ['Google AI Studio', 'Gemini Audio', 'Energetic', 'News', 'Free API'],
    defaultSpeed: 1.10,
    prosodyPacing: 'commercial',
    genreTag: 'Tech & Explainer',
    bestFor: 'News Summaries & Quick Explainers',
  },
  {
    id: 'google-gemini-enceladus',
    name: 'Enceladus (Google AI Studio — Commanding Epic)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Commanding, deep, powerfully resonant voice — built for cinematic trailers, epic reveals and battle documentary.',
    avatarColor: '#1e1b4b',
    tags: ['Google AI Studio', 'Gemini Audio', 'Commanding', 'Cinematic', 'Free API'],
    defaultSpeed: 0.85,
    prosodyPacing: 'trailer',
    defaultMasteringPreset: 'cinema_trailer',
    genreTag: 'Cinema & Trailer',
    bestFor: 'Cinematic Trailers & Epic Content',
  },
  {
    id: 'google-gemini-pulcherrima',
    name: 'Pulcherrima (Google AI Studio — Warm & Intimate)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Warm, intimate, deeply personal voice with emotional connection — perfect for personal development and story-driven content.',
    avatarColor: '#f43f5e',
    tags: ['Google AI Studio', 'Gemini Audio', 'Intimate', 'Personal', 'Free API'],
    defaultSpeed: 0.94,
    prosodyPacing: 'story',
    genreTag: 'Story & Audiobook',
    bestFor: 'Personal Development & Storytelling',
  },
  {
    id: 'google-gemini-rasalgethi',
    name: 'Rasalgethi (Google AI Studio — Dramatic & Dark)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Dramatic, dark, moody male narrator with rich lower register — ideal for true crime, thrillers and mystery content.',
    avatarColor: '#1f2937',
    tags: ['Google AI Studio', 'Gemini Audio', 'Dramatic', 'True Crime', 'Free API'],
    defaultSpeed: 0.91,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'True Crime',
    bestFor: 'True Crime & Mystery Thrillers',
  },
  {
    id: 'google-gemini-sadachbia',
    name: 'Sadachbia (Google AI Studio — Clear & Trustworthy)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Clear, trustworthy, even-paced male narrator — reliable for long-form explainers, educational and financial content.',
    avatarColor: '#0284c7',
    tags: ['Google AI Studio', 'Gemini Audio', 'Clear', 'Educational', 'Free API'],
    defaultSpeed: 0.98,
    prosodyPacing: 'documentary',
    genreTag: 'Tech & Explainer',
    bestFor: 'Educational & Financial Content',
  },
  {
    id: 'google-gemini-sadaltager',
    name: 'Sadaltager (Google AI Studio — Knowledgeable Host)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Knowledgeable, articulate, slightly academic male presenter — great for science channels, tech reviews and tutorials.',
    avatarColor: '#0e7490',
    tags: ['Google AI Studio', 'Gemini Audio', 'Academic', 'Tech', 'Free API'],
    defaultSpeed: 1.0,
    prosodyPacing: 'commercial',
    genreTag: 'Tech & Explainer',
    bestFor: 'Tech Reviews & Science Channels',
  },
  {
    id: 'google-gemini-sulafar',
    name: 'Sulafar (Google AI Studio — Soothing & Measured)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Soothing, measured, gently expressive female narrator — excellent for sleep content, wellness and guided journeys.',
    avatarColor: '#4f46e5',
    tags: ['Google AI Studio', 'Gemini Audio', 'Soothing', 'Wellness', 'Free API'],
    defaultSpeed: 0.86,
    prosodyPacing: 'story',
    genreTag: 'Story & Audiobook',
    bestFor: 'Sleep & Wellness Guides',
  },
  {
    id: 'google-gemini-achernar',
    name: 'Achernar (Google AI Studio — Polished Pro)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'female',
    category: 'preset',
    description: 'Polished, professional, studio-grade female narrator with broadcast clarity — ideal for corporate and B2B content.',
    avatarColor: '#0f766e',
    tags: ['Google AI Studio', 'Gemini Audio', 'Professional', 'Corporate', 'Free API'],
    defaultSpeed: 1.0,
    prosodyPacing: 'commercial',
    genreTag: 'Commercial & Ads',
    bestFor: 'Corporate & B2B Videos',
  },
  {
    id: 'google-gemini-achird',
    name: 'Achird (Google AI Studio — Friendly & Approachable)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Friendly, approachable, warm male presenter — perfect for beginner tutorials, how-to guides and community channels.',
    avatarColor: '#15803d',
    tags: ['Google AI Studio', 'Gemini Audio', 'Friendly', 'Tutorial', 'Free API'],
    defaultSpeed: 1.02,
    prosodyPacing: 'commercial',
    genreTag: 'Tech & Explainer',
    bestFor: 'How-To Guides & Community Content',
  },
  {
    id: 'google-gemini-algieba',
    name: 'Algieba (Google AI Studio — Deep & Reflective)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Deep, reflective, philosophical male voice — ideal for video essays, philosophy channels and thought leadership content.',
    avatarColor: '#6d28d9',
    tags: ['Google AI Studio', 'Gemini Audio', 'Reflective', 'Philosophy', 'Free API'],
    defaultSpeed: 0.92,
    prosodyPacing: 'documentary',
    genreTag: 'Documentary',
    bestFor: 'Video Essays & Philosophy Channels',
  },
  {
    id: 'google-gemini-algenib',
    name: 'Algenib (Google AI Studio — Crisp & Authoritative)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Crisp, authoritative, no-nonsense male narrator — excellent for historical facts, military docs and political analysis.',
    avatarColor: '#374151',
    tags: ['Google AI Studio', 'Gemini Audio', 'Authoritative', 'Military', 'Free API'],
    defaultSpeed: 0.95,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'Military & Political Documentaries',
  },
  {
    id: 'google-gemini-alnilam',
    name: 'Alnilam (Google AI Studio — Cosmic & Dramatic)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Vast, cosmic, slow-burning dramatic narrator — built for space documentaries, origin stories and universe-scale storytelling.',
    avatarColor: '#312e81',
    tags: ['Google AI Studio', 'Gemini Audio', 'Cosmic', 'Space Docs', 'Free API'],
    defaultSpeed: 0.87,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'Space & Cosmic Documentaries',
  },
  {
    id: 'google-gemini-zubenelgenubi',
    name: 'Zubenelgenubi (Google AI Studio — Steady & Deliberate)',
    engine: 'google',
    language: 'en',
    languageName: 'English (US)',
    gender: 'male',
    category: 'preset',
    description: 'Steady, deliberate, no-rush male narrator with deep measured delivery — perfect for ancient history and mythology.',
    avatarColor: '#713f12',
    tags: ['Google AI Studio', 'Gemini Audio', 'Steady', 'Ancient History', 'Free API'],
    defaultSpeed: 0.88,
    prosodyPacing: 'documentary',
    defaultMasteringPreset: 'broadcast_studio',
    genreTag: 'Documentary',
    bestFor: 'Ancient History & Mythology',
  },

  {
    id: 'google-bn-bashkar',
    name: 'Bashkar (Google — Bengali Presenter)',
    engine: 'google',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩/🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Natural, articulate Bengali narrator for documentary stories and videos.',
    avatarColor: '#0284c7',
    tags: ['Google Free', 'Bangla', 'Documentary', 'Natural'],
  },
  {
    id: 'google-bn-shikha',
    name: 'Shikha (Google — Bengali Melodious)',
    engine: 'google',
    language: 'bn',
    languageName: 'Bengali (বাংলা - 🇧🇩/🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'Soft, melodious Bengali narrative voice for literature and explainers.',
    avatarColor: '#db2777',
    tags: ['Google Free', 'Bangla', 'Melodious', 'Narrative'],
  },
  {
    id: 'google-hi-madhur',
    name: 'Madhur (Google — Hindi Narrator)',
    engine: 'google',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'male',
    category: 'preset',
    description: 'Clear, modern Hindi voice for cinema commentary and educational topics.',
    avatarColor: '#f97316',
    tags: ['Google Free', 'Hindi', 'Clear', 'Educational'],
  },
  {
    id: 'google-hi-swara',
    name: 'Swara (Google — Hindi Storyteller)',
    engine: 'google',
    language: 'hi',
    languageName: 'Hindi (हिन्दी - 🇮🇳)',
    gender: 'female',
    category: 'preset',
    description: 'Expressive Hindi narrative voice with natural cadence.',
    avatarColor: '#10b981',
    tags: ['Google Free', 'Hindi', 'Storyteller', 'Expressive'],
  },
  {
    id: 'google-es-camila',
    name: 'Camila (Google — Spanish Voice)',
    engine: 'google',
    language: 'es',
    languageName: 'Spanish (Español)',
    gender: 'female',
    category: 'preset',
    description: 'Fluent, clear Spanish narrative voice for global storytelling.',
    avatarColor: '#ef4444',
    tags: ['Google Free', 'Spanish', 'Fluent'],
  },
];

export const DEFAULT_BUILTIN_VOICES: VoiceProfile[] = RAW_DEFAULT_BUILTIN_VOICES.map((v) => ({
  ...v,
  sampleText: v.sampleText || VOICE_SAMPLE_PROMPTS[v.id] || '',
}));

